version: '1.0'
services:
  - name: mongodb
    type: mongodb
    version: 4.2
    configuration: StandAlone
    ports:
      - 27017
    remoteAccess: false
    volumes:
      - directory: /dump
    deployTo:
      - wekan

  - name: wekan
    type: docker
    image: quay.io/wekan/wekan:meteor-1.8
    version: latest
    ports:
      - 8080
    env:
      MONGO_URL: "mongodb://{{=service('mongodb').getMasterAlias()}}:27017/wekan"
      ROOT_URL: "http://{{=service('wekan').getNginxDomain()}}"
      MAIL_URL: null
      MAIL_FROM: null
      WITH_API: true
      BROWSER_POLICY_ENABLED: true
      TRUSTED_URL: null
      CORS: null
      MATOMO_SITE_ID: null
      MATOMO_DO_NOT_TRACK: null
      MATOMO_WITH_USERNAME: null
      WEBHOOKS_ATTRIBUTES: null
      DEBUG: null
      OAUTH2_ENABLED: null
      OAUTH2_CLIENT_ID: null
      OAUTH2_SERVER_URL: null
      OAUTH2_AUTH_ENDPOINT: null
      OAUTH2_USERINFO_ENDPOINT: null
      OAUTH2_TOKEN_ENDPOINT: null
      OAUTH2_ID_MAP: null
      OAUTH2_USERNAME_MAP: null
      OAUTH2_FULLNAME_MAP: null
      OAUTH2_EMAIL_MAP: null
      OAUTH2_ID_TOKEN_WHITELIST_FIELDS: null
      OAUTH2_REQUEST_PERMISSIONS: null
      DEFAULT_AUTHENTICATION_METHOD: null
      LDAP_ENABLE: null
      LDAP_PORT: null
      LDAP_HOST: null
      LDAP_BASEDN: null
      LDAP_LOGIN_FALLBACK: null
      LDAP_RECONNECT: null
      LDAP_TIMEOUT: null
      LDAP_IDLE_TIMEOUT: null
      LDAP_CONNECT_TIMEOUT: null
      LDAP_AUTHENTIFICATION: null
      LDAP_AUTHENTIFICATION_USERDN: null
      LDAP_AUTHENTIFICATION_PASSWORD: null
      LDAP_LOG_ENABLED: null
      LDAP_BACKGROUND_SYNC: null
      LDAP_BACKGROUND_SYNC_INTERVAL: null
      LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED: null
      LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS: null
      LDAP_ENCRYPTION: null
      LDAP_CA_CERT: null
      LDAP_REJECT_UNAUTHORIZED: null
      LDAP_USER_SEARCH_FILTER: null
      LDAP_USER_SEARCH_SCOPE: null

    comments:
      env:
        MAIL_URL: "smtp://user:pass@mailserver.example.com:25/"
        MAIL_FROM: "'Example Wekan Support <support@example.com>'"
        BROWSER_POLIY_ENABLED: "true (only allow trusted URL iframing) false (allow all iframing)"
        TRUSTED_URL: "https://intra.example.com"
        CORS: "*"
        MATOMO_SITE_ID: "1"
        MATOMO_DO_NOT_TRACK: "true"
        MATOMO_WITH_USERNAME: "true"
        WEBHOOKS_ATTRIBUTES: "cardId,listId,oldListId,boardId,comment,user,card,commentId (possible to leave out some)"
        DEBUG: "true (OIDC OAuth2 Debug)"
        OAUTH2_ENABLED: "true"
        OAUTH2_CLIENT_ID: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx (numbers and letters)"
        OAUTH2_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (numbers and letters)"
        OAUTH2_SERVER_URL: "https://login.microsoftonline.com/"
        OAUTH2_AUTH_ENDPOINT: "/oauth2/v2.0/authorize"
        OAUTH2_USERINFO_ENDPOINT: "https://graph.microsoft.com/oidc/userinfo"
        OAUTH2_TOKEN_ENDPOINT: "/oauth2/v2.0/token"
        OAUTH2_ID_MAP: "email"
        OAUTH2_USERNAME_MAP: "email"
        OAUTH2_FULLNAME_MAP: "name"
        OAUTH2_EMAIL_MAP: "email"
        OAUTH2_ID_TOKEN_WHITELIST_FIELDS: "[]"
        OAUTH2_REQUEST_PERMISSIONS: "[openid profile email]"
        DEFAULT_AUTHENTICATION_METHOD: "ldap"
        LDAP_ENABLE: "true"
        LDAP_PORT: "389"
        LDAP_HOST: "localhost"
        LDAP_BASEDN:"ou=user,dc=example,dc=org"
        LDAP_LOGIN_FALLBACK: "true"
        LDAP_RECONNECT: "true"
        LDAP_TIMEOUT: "10000 (ms)"
        LDAP_IDLE_TIMEOUT: "10000 (ms)"
        LDAP_CONNECT_TIMEOUT: "10000 (ms)"
        LDAP_AUTHENTIFICATION: "true"
        LDAP_AUTHENTIFICATION_USERDN: "cn=admin,dc=example,dc=org"
        LDAP_AUTHENTIFICATION_PASSWORD: "admin (The password for the search user)"
        LDAP_LOG_ENABLED: "true"
        LDAP_BACKGROUND_SYNC: "true"
        LDAP_BACKGROUND_SYNC_INTERVAL: "100 (ms)"
        LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=: "true"
        LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS: "true"
        LDAP_ENCRYPTION: "ssl (If using LDAPS) or false"
        LDAP_CA_CERT: "Cert for the LDAPS server. Example : LDAP_CA_CERT=-----BEGIN CERTIFICATE-----MIIE+zCCA+OFIdAgIC...-----END CERTIFICATE-----"
        LDAP_REJECT_UNAUTHORIZED: "false (Reject unauthorized cert)"
        LDAP_USER_SEARCH_FILTER: "(optional)"
        LDAP_USER_SEARCH_SCOPE: "base (search only in the provided DN), one (search only in the provided DN and one level deep), or sub (search the whole subtree)"
        LDAP_USER_SEARCH_FIELD: "uid (Which field is used to find the user)"
        LDAP_SEARCH_PAGE_SIZE: "Used for pagination (0=unlimited)"
        LDAP_SEARCH_SIZE_LIMIT: "The limit number of entries (0=unlimited)"
        LDAP_GROUP_FILTER_ENABLE: "Enable group filtering. Example: true"
        LDAP_GROUP_FILTER_OBJECTCLASS: "group"
        LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE: ""
        LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE: ""
        LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT: ""
        LDAP_GROUP_FILTER_GROUP_NAME: ""
        LDAP_UNIQUE_IDENTIFIER_FIELD: "guid (This field is sometimes class GUID, Globally Unique Identifier)"
        LDAP_UTF8_NAMES_SLUGIFY: "true (Convert the username to utf8)"
        LDAP_USERNAME_FIELD: "username (Which field contains the ldap username)"
        LDAP_FULLNAME_FIELD: "fullname (Which field contains the ldap fullname)"
        LDAP_MERGE_EXISTING_USERS: "true"
        LDAP_SYNC_USER_DATA: "true"
        LDAP_SYNC_USER_DATA_FIELDMAP: "{\"cn\":\"name\", \"mail\":\"email\"}"
        LDAP_SYNC_GROUP_ROLES: ""
        LDAP_DEFAULT_DOMAIN: "The default domain of the ldap it is used to create email if the field is not map correctly with the LDAP_SYNC_USER_DATA_FIELDMAP"
        LOGOUT_IN: "1 (The number of days)"
        LOGOUT_ON_HOURS: "9 (The number of hours)"
        LOGOUT_ON_MINUTES "55 (The number of minutes)"
    deployTo:
      - wekan

  - name: proxy
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    serviceFiles:
      - name: wekan
    deployTo:
      - wekan

hosts:
  - name: wekan
    requirements:
      cores: 1
      memory: 1
